-- solving_checkpoint: PK'yi UUID'den ayirip goz ile okunmasi kolay bir int id
-- ekliyor, ve checkpoint numarasini (solution_index/interval_size) hesaplanmis
-- bir kolon olarak ekliyor - sorgu yazarken "solution_index'te kac sifir var"
-- diye sasirmamak/yanlis sayilmamak icin.
--
-- - checkpoint_id (eski, UUID, PK) -> checkpoint_uuid olarak yeniden adlandirildi.
--   PK bu kolonda KALIYOR (sadece isim degisti, degeri/semantik'i degismedi).
-- - checkpoint_id (YENI): BIGINT, GENERATED BY DEFAULT AS IDENTITY, UNIQUE NOT NULL.
--   Var olan satirlara Postgres otomatik ardisik deger atar. Sadece okunabilirlik
--   icin - PK DEGIL, checkpoint_uuid PK olarak kaliyor.
-- - checkpoint_no: solution_index / interval_size, GENERATED ALWAYS ... STORED.
--   HER SATIR KENDI interval_size'ina gore hesaplanir - interval_size ileride
--   degisirse (2x/10x) bile eski satirlarin checkpoint_no'su BOZULMAZ, cunku
--   o satirin o anki interval_size'i ile hesaplanmis olarak SABIT kalir.
--
-- NOT: Postgres ADD COLUMN her zaman tablonun SONUNA ekler; "checkpoint_uuid'nin
-- hemen saginda" gibi fiziksel kolon sirasi icin tum tabloyu yeniden yazmak
-- gerekir - kucuk bir tablo icin bile gereksiz risk, burada YAPILMADI. \d
-- ciktisinda en sonda gorunur; SELECT'te istenen sirada listelenebilir.
--
-- Var olan bir DB'ye elle uygula:
--   docker exec -i dev-postgres psql -U pathexplorer -d pathexplorer < docker/initdb/06_solving_checkpoint_ids_and_checkpoint_no.sql

ALTER TABLE solving_checkpoint
    RENAME COLUMN checkpoint_id TO checkpoint_uuid;

ALTER TABLE solving_checkpoint
    ADD COLUMN checkpoint_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE solving_checkpoint
    ADD CONSTRAINT solving_checkpoint_checkpoint_id_key UNIQUE (checkpoint_id);

ALTER TABLE solving_checkpoint
    ADD COLUMN checkpoint_no BIGINT GENERATED ALWAYS AS (solution_index / interval_size) STORED;

COMMENT ON COLUMN solving_checkpoint.checkpoint_uuid IS 'satir kimligi (PK), eskiden checkpoint_id';
COMMENT ON COLUMN solving_checkpoint.checkpoint_id IS 'okunabilir ardisik int id (PK DEGIL) - sadece goz ile takip icin';
COMMENT ON COLUMN solving_checkpoint.checkpoint_no IS 'solution_index/interval_size, satirin KENDI interval_size''ina gore hesaplanir';
